# Generated by Django 5.0.1 on 2024-01-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=100)),
                ('fecha', models.DateField(max_length=300)),
                ('entregado', models.BooleanField()),
            ],
        ),
    ]
