# Generated by Django 5.0.1 on 2024-01-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
